version: '1.0'
services:
  dify_chat_openapi:
    container_name: dify_chat_openapi
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "3011:3011"
    restart: always
    environment: 
      - DIFY_API_URL=http://IP地址api的/v1
      - BOT_TYPE=Chat
