version: '1.0'
services:
  # dify_chat_openapi API relay service
  dify_chat_openapi:
   #  build: dify_chat_openapi
    image: difyitcg/dify_chat_openapi:latest
    container_name: dify_chat_openapi
    network_mode: bridge
    ports:
      - "3011:3011"
    restart: always
    environment: 
      - DIFY_API_URL=http://kb.itcg.cn/v1
      - BOT_TYPE=Chat
      - MODELS_NAME=gpt-3.5-turbo
